poly.exe : main.o poly.o opPoly.o
	gcc -o poly.exe -Wall main.o poly.o opPoly.o

main.o : main.c 
	gcc -c -Wall main.c

poly.o : poly.c 
	gcc -c -Wall poly.c

opPoly.o : opPoly.c
	gcc -c -Wall opPoly.c